### PR TITLE
shiny update

### PR DESCRIPTION
**Pull request by trafficonese**
A little update on the shiny functionality, which gives more flexibility and options. 

The functionality is wrapped in `use_svgzoom`, which allows to set some initializing CSS and JS-values.

I was thinking of including some selection / hovering effects, but for now I dont know how to connect the different HTML nodes. How can I find out the membership of nodes?

Could this info be integrated in the HTML somehow?

### CODE REVIEW

**Comment by nbarrowman** [comment]
This is great -- thanks!

Regarding your questions, I'm not very knowledgeable about this kind of thing. Here's what I can tell you ...

vtree uses `DiagrammeR::grViz` to build an `htmlwidget` object. I'm not sure if it's possible to have interaction between that object and Shiny in both directions. I found some discussion here: https://github.com/rich-iannone/DiagrammeR/issues/8  and here: https://github.com/rich-iannone/DiagrammeR/issues/290

**Comment by nbarrowman** [comment]
The functionality you've added is great. A number of people had asked if there was a way to zoom in/out of a variable tree. Here's a small modification of the example code you wrote:

```
library(shiny)
library(vtree)

## ui ##################
ui <- fluidPage(
  use_svgzoom(),
  tags$head(tags$style(HTML("body {background-color: #9c9ca096;}"))),
  helpText(div(style="font-weight: 800; font-size: large; color: black;",
               HTML("Zooming and Panning is possible with mouse-drag ",
               "and mouse-wheel <br>or with shortcuts; +,- and arrow-keys ",
               "and CTRL+Backspace to resize+fit+center the svg.."))),
  vtreeOutput("vtree", width = "100%", height = "500px")
)

makeserver <- function(...) {
  function(input, output, session) {
  output$vtree <- renderVtree({
    vtree(...,pngknit=FALSE)
  })
  }
}

shinyApp(ui, makeserver(FakeData,"Sex Severity Group Age id",horiz=FALSE))

```

The `makeserver` function lets me call vtree with whatever arguments I want.

**Comment by nbarrowman** [comment]
I have created a function called `svtree` to make it easy to open a shiny vtree app. See the develop branch for the latest development version.

Also, I have credited you with contributions. Please take a look at https://github.com/nbarrowman/vtree/blob/develop/DESCRIPTION

Are you ok with this? I have listed your github handle but I can put in your name if you prefer. Please let me know you preference.

**Comment by trafficonese** [comment]
Thanks, yes I am totally fine with it. 
You can put my real name and email there. 
Sebastian Gatscha, kona1@gmx.at

**Comment by nbarrowman** [comment]
Done (see fd0b3d2acc5b8bf31c050f6d672d3bca31e4fa4a).

**Pull request merged**
